require 'pathname'
require 'tmpdir'

module CedarTargetiLearn_Tests
  UI_SPECS_TARGET_NAME = "iLearn Tests"
  CONFIGURATION = "Release"

  PROJECT_ROOT = Pathname.new(File.dirname(__FILE__)).parent.to_s
  BUILD_DIR = File.join(PROJECT_ROOT, "build")

  class << self
    def in_project_dir
      original_dir = Dir.pwd
      Dir.chdir(PROJECT_ROOT)

      yield

      ensure
      Dir.chdir(original_dir)
    end

    def destination_for_ios_sdk(version)
      if `xcodebuild -showsdks`.include? "iphonesimulator8.0"
        "OS=#{version},name=iPhone 5s"
      else
        "OS=#{version},name=iPhone 4s"
      end
    end

    def deployment_target_sdk_version
      in_project_dir do
        `xcodebuild -showBuildSettings -target #{UI_SPECS_TARGET_NAME} | grep IPHONEOS_DEPLOYMENT_TARGET | awk '{print $3 }'`.strip
      end
    end

    def deployment_target_sdk_dir
      @sdk_dir ||= %x[ xcrun -sdk iphonesimulator#{deployment_target_sdk_version} -show-sdk-path ].strip
    end

    # Xcode 4.3 stores its /Developer inside /Applications/Xcode.app, Xcode 4.2 stored it in /Developer
    def xcode_developer_dir
      `xcode-select -print-path`.strip
    end

    def build_dir(effective_platform_name)
      File.join(BUILD_DIR, CONFIGURATION + effective_platform_name)
    end

    def is_run_unit_tests_deprecated?
      system("cat #{xcode_developer_dir}/Tools/RunUnitTests | grep -q 'RunUnitTests is obsolete.'")
    end

    def system_or_exit(cmd, stdout = nil)
      puts "Executing #{cmd}"
      cmd += " >#{stdout}" if stdout
      system(cmd) or raise "******** Build failed ********"
    end

    def run_cmd_and_grep_for_failure(cmd)
      puts "Executing #{cmd}"
      puts result = %x[#{cmd} 2>&1]
      if result.index(/Test Case.*failed/)
        exit(1)
      else
        exit(0)
      end
    end

    def with_env_vars(env_vars)
      old_values = {}
      env_vars.each do |key,new_value|
        old_values[key] = ENV[key]
        ENV[key] = new_value
      end

      yield

      env_vars.each_key do |key|
        ENV[key] = old_values[key]
      end
    end

    def output_file(target)
      output_dir = if ENV['IS_CI_BOX']
        ENV['CC_BUILD_ARTIFACTS']
      else
        Dir.mkdir(BUILD_DIR) unless File.exists?(BUILD_DIR)
        BUILD_DIR
      end

      output_file = File.join(output_dir, "#{target}.output")
      puts "Output: #{output_file}"
      output_file
    end

    def kill_simulator
      system %Q[killall -m -KILL "gdb"]
      system %Q[killall -m -KILL "otest"]
      system %Q[killall -m -KILL "iPhone Simulator"]
    end
  end
end

desc "Clean build directory"
task :clean_iLearn_Tests do
  CedarTargetiLearn_Tests.system_or_exit "rm -rf #{CedarTargetiLearn_Tests::BUILD_DIR}/*", CedarTargetiLearn_Tests.output_file("clean")
end

desc "Build iLearn_Tests OCUnit application specs"
task :build_iLearn_Tests => :clean_iLearn_Tests do
  CedarTargetiLearn_Tests.kill_simulator
  CedarTargetiLearn_Tests.system_or_exit "pushd #{CedarTargetiLearn_Tests::PROJECT_ROOT} && xcodebuild -target 'iLearn Tests' -configuration #{CedarTargetiLearn_Tests::CONFIGURATION} -sdk iphonesimulator#{CedarTargetiLearn_Tests.deployment_target_sdk_version} clean build ARCHS=i386 TEST_AFTER_BUILD=NO GCC_SYMBOLS_PRIVATE_EXTERN=NO SYMROOT='#{CedarTargetiLearn_Tests::BUILD_DIR}' && popd", CedarTargetiLearn_Tests.output_file("iLearn Tests-AppBuild")
  CedarTargetiLearn_Tests.system_or_exit "pushd #{CedarTargetiLearn_Tests::PROJECT_ROOT} && xcodebuild -target #{CedarTargetiLearn_Tests::UI_SPECS_TARGET_NAME} -configuration #{CedarTargetiLearn_Tests::CONFIGURATION} -sdk iphonesimulator#{CedarTargetiLearn_Tests.deployment_target_sdk_version} build ARCHS=i386 GCC_SYMBOLS_PRIVATE_EXTERN=NO TEST_AFTER_BUILD=NO SYMROOT='#{CedarTargetiLearn_Tests::BUILD_DIR}' && popd", CedarTargetiLearn_Tests.output_file("iLearn Tests-SpecBuild")
end

desc "Run iLearn_Tests OCUnit application specs"
task :iLearn_Tests => :build_iLearn_Tests do
  CedarTargetiLearn_Tests.system_or_exit "cd #{CedarTargetiLearn_Tests::PROJECT_ROOT} && xcodebuild test -scheme iLearn -configuration #{CedarTargetiLearn_Tests::CONFIGURATION} -destination '#{CedarTargetiLearn_Tests.destination_for_ios_sdk(CedarTargetiLearn_Tests.deployment_target_sdk_version)}' ARCHS=i386 SYMROOT='#{CedarTargetiLearn_Tests::BUILD_DIR}' | tee /dev/stderr | grep -q 'with 0 failures'"
end
